### ISSUE TITLE
Where is sentences_just_one_position.csv?

### ISSUE THREAD

**Issue by felicitia** [fromm-m/aaai2021-am-peer-reviews#3]
Hello @fromm-m I'm trying to train the model following "5. Work with Models", but I couldn't seem to find `sentences_just_one_position.csv` that is required to run `s_data_preprocess.py`. Could you please point to where it is?

**Comment by fromm-m** [comment]
hey you can find them now under 5

**Comment by felicitia** [comment]
great thank you @fromm-m !
